### ISSUE TITLE
The first characters are missing from FLEX messages

### ISSUE THREAD

**Issue by andrewdefilippis** [EliasOenal/multimon-ng#139] opened 2019-10-05 00:04 UTC
https://github.com/EliasOenal/multimon-ng/blob/1168661931a43d986a89efab5b8ae390f0e2f486/demod_flex.c#L527
When removing `mw1++`, the resulting message begins with `ALN From:` instead of `ALN om:`.

The issue with this is that a variable number of extra characters appear to be inserted at the beginning of the message:
* `ALN fFrom:`
* `ALN <From:`
* `ALN vFrom:`

The parsing of where a message begins and ends appears to be inconsistent.  It doesn't look like the message body is being decoded properly.

**Comment by rob0101** [comment] 2019-10-19 07:04
Are all your messages starting with missing letters ?

All my messages are coming through correct.

**Comment by rlerner** [comment] 2019-11-19 18:19
I'm also seeing that FLEX messages are dropping roughly the first three characters of any alphanumeric "ALN" message. I haven't modified the source to confirm yet.

**Comment by rfarley3** [comment] 2020-05-24 05:03
I had the same problems, I fixed it against some test data, but I'll need guidance on how the PRs should be structured. I also patched a stack corruption bug, but I don't have sharable data to reproduce.

Here is the summary, I mostly just reconciled this code with the PDW/Flex.cpp code:
* Frag location is dependent on whether it is a long address. The code uses mw1, but it can also be from the block after viw. 
* Long address detection is missing a condition and has a typo in another
* mw1 and mw2 change depending on if it is a long address and/or group message

**Comment by rfarley3** [comment] 2020-05-24 18:06
I had been dev and testing on a laptop. After I compiled my changes on a Pi, I ran into endianness issues. Probably my code, but either way I'll need to fix those.

**Comment by EliasOenal** [comment] 2020-05-25 15:11
Regarding the pull request there's not too much to consider. Authorship should be established. For anything that's more than a simple bug fix we would like to have your name in the header of the file. If the change isn't trivial to understand a short explanation would be nice and, if available, samples to verify the change would appreciated.

**Comment by Zanoroy** [comment] 2020-09-21 02:57
@rfarley3 Do you have the changes you made to the code? I checked your Fork but it doesn't appear to be any different from EliasOenal's master. 

I can add your changes and get them pulled into the master source if you like.

**Comment by MS3FGX** [comment] 2020-09-24 00:05
Just to confirm, I'm seeing the same missing characters as @andrewdefilippis on master branch, but the fork created by @rfarley3 seems to fix the issue.

**Comment by Zanoroy** [comment] 2020-09-24 00:21
@MS3FGX I agree, but I wanted @rfarley3 to confirm it ready to be merged: e.g. Bugs fixed (as much as possible) and tested. I'm more than happy to pull the changes across.

**Comment by rfarley3** [comment] 2020-09-24 00:29
I hit some public release paperwork at work. Then lost track of time and haven't been able to polish my branch at home to push to my GitHub fork. Sorry for keeping your all loops open on this. 

While you should be fine taking my fork as is, I do have further modified code that has been running stable for a few months with full message decoding and no fmt str bugs. I had to maintain a version for a PR with minimal changes so you all could diff easy; and a version that addressed other smaller unrelated decoding, bugs, and consistency things. This got me a bit befuddled. I will do a diff of my private local code vs my public fork and comment back here if there is much worth waiting on. It may be a few days before I have time. Again apologies on the delay for finishing this up.

**Comment by Zanoroy** [comment] 2020-09-24 00:33
@rfarley3 Perfect thanks. 

I started walking through the changes you have made and you have addresses 70% of my 'TODO' list so it would be fantastic to pull your changes in and have @EliasOenal to add you to the contributors list. I have a few changes that will need to be manually added again after we pull yours across but awesome job.

**Comment by rfarley3** [comment] 2020-09-28 14:18
I just verified the diff, and I have no unpublished code. It fixes #139 and is tested.

@Zanoroy FYSA there are 2 branches: 139-characters-missing-from-flex and 139-mod. I put potentially controversial changes in 139-mod, highly personalized changes that I was worried would step on toes or you all might feel muddy the branch. Please let me know which you would like me to create the PR from, or if you want a 3rd with certain cherry-picks.

The mod branch has the following additional changes you probably want:
* binary page handler
* avoids bare % in printf (I was hoping to have fun with this at the next wctf, but it's better to not sit on)

And some you probably don't want:
* All output conforms to the same syntax, with fixed widths---this will more than likely to break pagermon ingest for people, but I have a mmng to json converter I'm working on that pagermon can ingest, and I can create a PR for it later
* Deleted commented code---seemed to be issues already solved, but I don't want to annoy primary devs

**Comment by Zanoroy** [comment] 2020-09-28 21:28
@rfarley3 That's great.

I had a very quick look, the two items you identified as "probably don't want" I have actually done the same in my fork anyway (maybe not exactly the same). So I would include them, please feel free to add a pull request for it all. 

I am currently _attempting_ to merge our forks and branches together on my local system because I know a couple of my local changes will have merging conflicts.

Could you please let me know when you have created the PR. 

Cheers

**Comment by rfarley3** [comment] 2020-10-03 21:25
@Zanoroy PR is created

**Comment by Zanoroy** [comment] 2020-10-04 09:22
@rfarley3 thanks

@EliasOenal any chance you can send me a PM when you scored accept the PR.

**Closed** 2020-11-02 14:04 UTC
Labels: bug, help wanted
