### ISSUE TITLE
-a FLEX  dropping first character of some message on regular basis

### ISSUE THREAD

**Issue by rob0101** [EliasOenal/multimon-ng#95] opened 2018-02-08 22:44 UTC
I have access to a couple of hardware based decoders that I'm able to compare the output with and notice the first character of some messages is dropped by multimon-ng

e.g.

Good:
1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7557
1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7557
1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7557

Bad:
1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7559
1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7559
1900253 | HIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  7559

I see this  often with these periodic (sent every minute) messages, but it also happens at much reduced regularity with others.

1916025 | BL81 PR: 3 - HALBURY D00323 Disp: 09:12 Unconsciou
1916025 | BL81 PR: 3 - HALBURY D00323 Disp: 09:12 Unconsciou
1916025 | L81 PR: 3 - HALBURY D00323 Disp: 09:12 Unconsciou

I'm decoding with ...
rtl_fm -f 148812500 -s22050  | multimon-ng -a FLEX -f alpha -t raw -v3 -

**Comment by rob0101** [comment] 2018-02-10 07:29
Interesting that this message, sent to two capcodes got the first character chopped for both..

1916082 | V126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER
1916082 | V126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER
1916082 | 126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER

1916084 | V126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER
1916084 | V126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER
1916084 | 126 PR: 8 - : @VHL VICTOR HARBOR 313 L 1 D00755 Disp: 17:36 TRANSFER

Here's one more example, maybe it'll help show a pattern.

1800165 | MFS: *CFSRES INC0103 10/02/18 17:16 RESPOND GRASS FIRE, ALARM LEVEL: 1, CURTIS RD MUNNO PARA,MAP:ADL 42 C10,TG 102, ==1X2 M LENGTH PLANTS ON FIRE IN MEDIAN STRIP :AIRDESK4 DALK24 DALK34P R ELZ339 :
1800165 | FS: *CFSRES INC0103 10/02/18 17:16 RESPOND GRASS FIRE, ALARM LEVEL: 1, CURTIS RD MUNNO PARA,MAP:ADL 42 C10,TG 102, ==1X2 M LENGTH PLANTS ON FIRE IN MEDIAN STRIP :AIRDESK4 DALK24 DALK34P R ELZ339 :
1800165 | MFS: *CFSRES INC0103 10/02/18 17:16 RESPOND GRASS FIRE, ALARM LEVEL: 1, CURTIS RD MUNNO PARA,MAP:ADL 42 C10,TG 102, ==1X2 M LENGTH PLANTS ON FIRE IN MEDIAN STRIP :AIRDESK4 DALK24 DALK34P R ELZ339 :

**Comment by rob0101** [comment] 2018-02-10 22:22
Reverting to a version of parse_alphanumeric() from June seems to clear this problem. The rewrite of it has introduced problems.

I would also like this to be considered..

 static void parse_alphanumeric(struct Flex * flex, unsigned int * phaseptr, char PhaseNo, int mw1, int mw2, int flex_groupmessage) {
        if (flex==NULL) return;
        verbprintf(3, "FLEX: Parse Alpha Numeric\n");
        int frag;
-       //   int cont;
+       int cont;
+       char frag_flag = 'K';
 
        frag = ( phaseptr[mw1] >> 11) & 0x03;
+       cont = (phaseptr[mw1] >> 0x0A) & 0x01;
+
+       if (cont == 1) frag_flag = 'F';
+       if (cont == 0 && frag == 0) frag_flag = 'C';


and then find a place in the output to display frag_flag.  I'm currently sending it in the place where PhaseNo is printed.

-                               flex->Sync.baud, flex->Sync.levels, PhaseNo, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
+                               flex->Sync.baud, flex->Sync.levels, frag_flag, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
  
but that's not a good long term place for it.

What does frag_flag do ?

if frag_flag is K    then the message is complete and O'K' to display to the world.
if frag_flag is F   then the message is a 'F'ragment and needs a 'C'ontinuation message to complete it.  message = fragment + continuation
if frag_flag is C   then the message is a 'C'ontinuation of another fragmented message

With these 3 options in the output, later software can buffer types C and F and send them out when the missing pieces turn up.  The order of C and F type pieces is unpredictable and they can be separated by other messages for different capcodes, so some smart buffering is needed.

With these changes and a script to handle the F & C messages my pi + multimon-ng is now in complete sync with hardware decoders and is faster too.  The pi's is on the slowest network of the 3 and outruns one $700 h/w decoder most of the time.

18-02-11 08:30:02  HW1  1909119 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:03  HW2  1909119 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:03  mng  1909119 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:03  HW1  1909109 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:03  mng  1909109 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:03  HW2  1909109 | Conc QRV is at Emu Flat Fire as part of strike team as of 0700hrs Mark, SFF2.
18-02-11 08:30:10  mng  1900159 | mhs-watchdog 180211083003
18-02-11 08:30:10  HW1  1900159 | mhs-watchdog 180211083003
18-02-11 08:30:10  HW2  1900159 | mhs-watchdog 180211083003
18-02-11 08:31:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0409
18-02-11 08:31:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0409
18-02-11 08:31:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0409
18-02-11 08:32:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0410
18-02-11 08:32:01  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0410
18-02-11 08:32:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0410
18-02-11 08:33:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0411
18-02-11 08:33:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0411
18-02-11 08:33:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0411
18-02-11 08:34:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0412
18-02-11 08:34:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0412
18-02-11 08:34:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0412
18-02-11 08:35:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0413
18-02-11 08:35:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0413
18-02-11 08:35:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0413
18-02-11 08:35:06  mng  1900159 | mhs-watchdog 180211083502
18-02-11 08:35:06  HW1  1900159 | mhs-watchdog 180211083502
18-02-11 08:35:06  HW2  1900159 | mhs-watchdog 180211083502
18-02-11 08:36:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0414
18-02-11 08:36:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0414
18-02-11 08:36:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0414
18-02-11 08:37:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0415
18-02-11 08:37:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0415
18-02-11 08:37:01  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0415
18-02-11 08:38:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0416
18-02-11 08:38:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0416
18-02-11 08:38:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0416
18-02-11 08:38:08  HW1  1900159 | mhs-watchdog 180211083802
18-02-11 08:38:08  mng  1900159 | mhs-watchdog 180211083802
18-02-11 08:38:08  HW2  1900159 | mhs-watchdog 180211083802
18-02-11 08:38:14  HW1  1925605 | F72 PR: 3 - : ASSIST LIFT HENLEY BEACH 116 A 11 D00271 Disp: 08:38 Allergies
18-02-11 08:38:14  mng  1925605 | F72 PR: 3 - : ASSIST LIFT HENLEY BEACH 116 A 11 D00271 Disp: 08:38 Allergies
18-02-11 08:38:51  HW1  1925568 | EW77 PLEASE ADVISE IF YOU HAVE HANDED OVER - IF THERE ARE DELAYS PLEASE CALL HNC 1300 117 362
18-02-11 08:38:52  HW2  1925568 | EW77 PLEASE ADVISE IF YOU HAVE HANDED OVER - IF THERE ARE DELAYS PLEASE CALL HNC 1300 117 362
18-02-11 08:38:52  mng  1925568 | EW77 PLEASE ADVISE IF YOU HAVE HANDED OVER - IF THERE ARE DELAYS PLEASE CALL HNC 1300 117 362
18-02-11 08:39:00  HW1  1925562 | GX77 PR: 5 - ADELAIDE 4 A 1 D00272 Disp: 08:38 Sick Perso
18-02-11 08:39:01  HW2  1925562 | GX77 PR: 5 - ADELAIDE 4 A 1 D00272 Disp: 08:38 Sick Perso
18-02-11 08:39:01  mng  1925562 | GX77 PR: 5 - ADELAIDE 4 A 1 D00272 Disp: 08:38 Sick Perso
18-02-11 08:39:02  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0417
18-02-11 08:39:02  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0417
18-02-11 08:39:02  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0417
18-02-11 08:39:08  mng  1931794 | PLEASE PHONE xxxx ON HIS MOBILE
18-02-11 08:39:08  HW1  1931794 | PLEASE PHONE xxxx ON HIS MOBILE
18-02-11 08:39:08  HW2  1931794 | PLEASE PHONE xxxx ON HIS MOBILE
18-02-11 08:39:17  mng  1932351 | PA820 PR: 2 - PARAFIELD GARDENS 70 E 6 D00273 Disp: 08:23 Unconsciou
18-02-11 08:39:17  HW1  1932351 | PA820 PR: 2 - PARAFIELD GARDENS 70 E 6 D00273 Disp: 08:23 Unconsciou
18-02-11 08:39:18  HW2  1932351 | PA820 PR: 2 - PARAFIELD GARDENS 70 E 6 D00273 Disp: 08:23 Unconsciou
18-02-11 08:40:00  mng  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0418
18-02-11 08:40:00  HW1  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0418
18-02-11 08:40:01  HW2  1900253 | THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  0418
18-02-11 08:40:27  mng  1916029 | BU81 PR: 5 - BURRA SBA 1 H 11 D00274 Disp: 08:40 Falls
18-02-11 08:40:27  HW2  1916029 | BU81 PR: 5 - BURRA SBA 1 H 11 D00274 Disp: 08:40 Falls
18-02-11 08:40:27  HW1  1916029 | BU81 PR: 5 - BURRA SBA 1 H 11 D00274 Disp: 08:40 Falls

**Comment by jklnz** [comment] 2018-02-11 01:44
@rob0101 Yeah I like your idea of printing the frag and cont statuses, I have modified PDW to do that so I can better post process messages. By printing them out we atleast allow whatever program is using the data to be able to combine messages better.

**Comment by rob0101** [comment] 2018-02-11 11:35
I looked at using pdw years back and was put off by the half-arsed attempt at dealing with fragmented messages.  Nothing worse than discarding useful information that can't be rediscovered later.

**Comment by jklnz** [comment] 2018-02-11 21:23
Yeah I agree there, I had to modify PDW to get it to output the information. Unfortunately I haven't been able to get as high decode percentage using any other apps than I do on PDW.

**Comment by rob0101** [comment] 2018-02-11 22:19
Interesting.  I'm seeing near 100% with this new setup, and that's with the system and 6" antenna in a cupboard.  I found a sweet spot for the antenna and it's happiest pointing sideways instead of upwards.  Move it 20cm and it misses lots.

I did notice that with the current demod_flex.c some messages did go astray, probably due to the loss of bytes here and there.

My hardware decoder is pretty much useless without an external antenna at the same location - lots of corruption.

**Comment by jklnz** [comment] 2018-02-12 00:16
That is very interesting, I might give multimon another go and see if it has improved. I dont know if this might make it worse but our network also transmits POCSAG512/1200 messages on the same frequency.

Haha yeah I have the same things with the antennas, they like to be in one place only.

Which SDR device do you use?

**Comment by rob0101** [comment] 2018-02-12 00:48
> Using device 0: Generic RTL2832U OEM
> Found Rafael Micro R820T tuner

**Comment by rob0101** [comment] 2018-02-12 00:55
@jklnz  - don't use the current version of parse_alphanumeric() in demod_flex.c it could mess things up.

this is the one I'm using:
<pre>
static void parse_alphanumeric(struct Flex * flex, unsigned int * phaseptr, char PhaseNo, int mw1, int mw2, int flex_groupmessage) {
        if (flex==NULL) return;
        verbprintf(3, "FLEX: Parse Alpha Numeric\n");
        int frag;
        int cont;
        char frag_flag = 'K';

        frag = ( phaseptr[mw1] >> 11) & 0x03;
        cont = (phaseptr[mw1] >> 0x0A) & 0x01;

        if (cont == 1) frag_flag = 'F';
        if (cont == 0 && frag == 0) frag_flag = 'C';
verbprintf(1,  "FLEX: f=%d c=%d FL=%c\n", frag, cont, frag_flag);

        mw1++;

        int i;
        time_t now=time(NULL);
        struct tm * gmt=gmtime(&now);
        char message[1024];
        int  currentChar = 0; 

        for (i = mw1; i <= mw2; i++) {
                unsigned int dw =  phaseptr[i];
                unsigned char ch;

                if (i > mw1 || frag != 0x03) {
                        ch = dw & 0x7F;
                        if (ch != 0x03) {
                                message[currentChar] = ch;      
                                //verbprintf(0, "%c", ch);
                                currentChar++;
                        }
                }

                ch = (dw >> 7) & 0x7F;
                if (ch != 0x03) {
                        message[currentChar] = ch;      
                        //verbprintf(0, "%c", ch);
                        currentChar++;
                }

                ch = (dw >> 14) & 0x7F;
                if (ch != 0x03) {
                        message[currentChar] = ch;      
                        //verbprintf(0, "%c", ch);
                        currentChar++;
                }
        }

        if(flex_groupmessage == 1) {
                verbprintf(0,  "FLEX: %04i-%02i-%02i %02i:%02i:%02i %i/%i/%c %02i.%03i [%09lld] GPN ", gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,
                                flex->Sync.baud, flex->Sync.levels, frag_flag, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
        } else {
                verbprintf(0,  "FLEX: %04i-%02i-%02i %02i:%02i:%02i %i/%i/%c %02i.%03i [%09lld] ALN ", gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,
                                flex->Sync.baud, flex->Sync.levels, frag_flag, flex->FIW.cycleno, flex->FIW.frameno, flex->Decode.capcode);
        }
        for(int x = 0; x < currentChar; x++)
        {
                verbprintf(0, "%c", message[x]);
        }
        verbprintf(0, "\n");
        if(flex_groupmessage == 1) {
                int groupbit = flex->Decode.capcode-2029568;
                if(groupbit < 0) return;
                        
                int endpoint = flex->GroupHandler.aGroupCodes[groupbit][CAPCODES_INDEX];
                for(int g = 1; g <= endpoint;g++)
                {
                        verbprintf(1, "FLEX Group message output: Groupbit: %i Total Capcodes; %i; index %i; Capcode: [%09lld]\n", groupbit, endpoint, g, flex->GroupHandler.aGroupCodes[groupbit][g]);

                        verbprintf(0,  "FLEX: %04i-%02i-%02i %02i:%02i:%02i %i/%i/%c %02i.%03i [%09lld] ALN ", gmt->tm_year+1900, gmt->tm_mon+1, gmt->tm_mday, gmt->tm_hour, gmt->tm_min, gmt->tm_sec,
                                        flex->Sync.baud, flex->Sync.levels, frag_flag, flex->FIW.cycleno, flex->FIW.frameno, flex->GroupHandler.aGroupCodes[groupbit][g]);

                        verbprintf(0, "%s\n", message);
                }
                // reset the value 
                flex->GroupHandler.aGroupCodes[groupbit][CAPCODES_INDEX] = 0;   
        }

}
</PRE>

I also uncommented the i++;    here:

<PRE>
                        verbprintf(4, "FLEX: Found 'Long Address' bit, ignoring as I think this is handled incorrectly at the moment issue#79\n");
//                        i++;
</PRE>

based on a hunch rather than evidence.

**Comment by jklnz** [comment] 2018-02-12 01:26
Thanks for that @rob0101 I will give that a try tonight. Yeah I think you might be right with that, but we'll see.

**Comment by Zanoroy** [comment] 2018-04-11 01:33
Guys,
     I have only just seen this (I didn't receive a notification that the issue was raised). I'll have a look at the cause and fix it up in the master rep, I think it was introduced with the group message handling.

If you find issues in the flex I can normally be notified if you include an @zanoroy in the issue.. 

Cheers

**Comment by Zanoroy** [comment] 2018-04-11 02:39
@rob0101
     Ok, I have rolled back the for loop in the latest version (with the chopped character) to the previously used loop (without the chopped character) I have tested it with the recordings I have, but I have limited recording that would show the issue and am not in position to sniff the SAGRN as you are using.

Also I implemented the K, F and C frag flags you introduced into the base version (although I also kept the 'PhaseNo' in the output).

if you wouldn't mind downloading the version I have located [https://github.com/Zanoroy/multimon-ng](https://github.com/Zanoroy/multimon-ng) if you are happy with it I can create a pull request and get the master version fixed.

I need to also find a corrupt messaging handling issue in the group messaging section (Issue #101)

Cheers

**Comment by rob0101** [comment] 2018-04-11 03:36
@Zanoroy - the output is bad ..


FLEX: 2018-04-11 03:32:13 1600/2/K/A 08.007 [001900253] ALN THIS IS A TEST PERIODIC PAGE SEQUENTIAL NUMBER  5700
FLEX: 2018-04-11 03:32:19 1600/2/K/A 08.010 [001900159] ALN mhs-watchdog 180411130215AGE SEQUENTIAL NUMBER  5700
FLEX: 2018-04-11 03:32:51 1600/2/K/A 08.027 [001925618] ALN PF89 PR: 8 - : @LMH ELIZABETH VALE 61 N 11 D00604 Disp: 13:02 Discharge
FLEX: 2018-04-11 03:33:00 1600/2/K/A 08.032 [001925585] ALN AS122 PR: 2 - ADELAIDE 4 A 7 D00605 Disp: 13:02 Heart Prob:02 Discharge

The 2nd message is shorter than the 1st and includes part of the 1st.

This issue repeats.

**Comment by Zanoroy** [comment] 2018-04-11 03:41
@rob0101 thanks for the fast response. 

Any chance you could capture some of that data (the raw audio) and upload it for me to debug with please?

I am in Adelaide at the moment but I don't have my receiving rig setup.

**Comment by Zanoroy** [comment] 2018-04-11 03:47
@rob0101 Hey,
      Damn, I see what I did. I didn't null terminate the message array and therefore the messages are messed up.

Shoot me a PM to zanoroy@gmail.com and I can give you my number if you want to have a chat.

**Comment by Zanoroy** [comment] 2018-04-11 03:56
I have fixed the missed null terminator and uploaded the code. I have managed to capture some raw data and am currently continuing to test.

if you grab the latest copy it should have addressed the issues.

cheers

**Comment by rob0101** [comment] 2018-04-11 04:06
@Zanoroy ha, no problem.  Looks fixed now.

I'll monitor it for a few hours and let you know.

I'm comparing it against 2 other PIs and a hardware decoder. Look clean and consistent so far.

**Comment by rob0101** [comment] 2018-04-11 06:25
No issues to report with this version.

thanks

**Comment by Zanoroy** [comment] 2018-04-11 06:29
Awesome, sorry I hadn't seen the  issue earlier.

Cheers

**Comment by Zanoroy** [comment] 2018-04-17 22:18
@rob0101 if you are happy could you please close this issue.

**Closed** 2018-04-17 23:32 UTC
